/* SPDX-License-Identifier: MPL-2.0 */
#include <maelys/cli.h>
#include <maelys/datalog.h>
#include <maelys/datalog_builders.h>
#include <maelys/datalog_program.h> /* public, read-only program inspection */

#include "reader.h"
#include "datalog_schemas.h" /* generated by maelys-cli-embed */

#include <errno.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

#ifndef DATALOG_CLI_VERSION
#error "DATALOG_CLI_VERSION must come from the package VERSION"
#endif

#if defined(MAELYS_DATALOG_EXTENSION_H) || defined(MAELYS_DATALOG_BACKEND_H) || \
    defined(MAELYS_DATALOG_MODULE_H)
#error "The CLI must not include Datalog provider or module APIs"
#endif

typedef struct {
    datalog_cli_domain_t *domains;
    size_t domain_count;
    char *source;
    maelys_datalog_policy_t *policy;
    maelys_datalog_session_t *session;
    maelys_datalog_result_t *result;
    datalog_cli_facts_t facts;
} state_t;

static void cleanup(state_t *state) {
    if (state->result) (void)maelys_datalog_result_free(state->result);
    if (state->session) (void)maelys_datalog_session_free(state->session);
    if (state->policy) (void)maelys_datalog_policy_free(state->policy);
    for (size_t i = 0; i < state->domain_count; ++i)
        datalog_cli_domain_free(&state->domains[i]);
    free(state->domains);
    free(state->source);
    datalog_cli_facts_free(&state->facts);
    memset(state, 0, sizeof(*state));
}

static int failure(maelys_cli_context_t *context, const char *code,
                   const char *message) {
    return maelys_cli_fail(context, code, NULL, "%s", message);
}

static int status_failure(maelys_cli_context_t *context,
                          maelys_datalog_status_t status,
                          const maelys_datalog_diagnostic_t *diagnostic) {
    const char *message = diagnostic && diagnostic->message[0]
        ? diagnostic->message : maelys_datalog_status_name(status);
    const char *code = status == MAELYS_DATALOG_STATUS_NOT_FOUND
        ? MAELYS_CLI_CODE_NOT_FOUND : status == MAELYS_DATALOG_STATUS_UNSUPPORTED
        ? MAELYS_CLI_CODE_UNSUPPORTED : status == MAELYS_DATALOG_STATUS_IO
        ? MAELYS_CLI_CODE_IO_FAILED :
        (status == MAELYS_DATALOG_STATUS_INTERNAL ||
         status == MAELYS_DATALOG_STATUS_INVALID_STATE)
        ? MAELYS_CLI_CODE_UNEXPECTED : MAELYS_CLI_CODE_VALIDATION_FAILED;
    return failure(context, code, message);
}

static int read_source(const char *path, char **out, size_t *length) {
    FILE *file = fopen(path, "rb");
    if (!file) return -1;
    size_t size = 0, capacity = 4096;
    const size_t limit = 16u * 1024u * 1024u;
    char *buffer = malloc(capacity + 1u);
    if (!buffer) { fclose(file); return -1; }
    for (;;) {
        if (size == capacity) {
            if (capacity >= limit) {
                int next = fgetc(file);
                if (next != EOF || ferror(file)) {
                    errno = ferror(file) ? EIO : EFBIG;
                    free(buffer); fclose(file); return -1;
                }
                break;
            }
            capacity *= 2u;
            char *grown = realloc(buffer, capacity + 1u);
            if (!grown) { free(buffer); fclose(file); return -1; }
            buffer = grown;
        }
        size_t n = fread(buffer + size, 1u, capacity - size, file);
        size += n;
        if (n == 0) {
            if (ferror(file)) { free(buffer); fclose(file); return -1; }
            break;
        }
    }
    fclose(file);
    if (memchr(buffer, 0, size)) { errno = EINVAL; free(buffer); return -1; }
    buffer[size] = 0;
    *out = buffer;
    *length = size;
    return 0;
}

static void diagnostic_json(maelys_cli_json_writer_t *json,
                            const maelys_datalog_diagnostic_t *d) {
    (void)maelys_cli_json_begin_object(json);
    (void)maelys_cli_json_key_string(json, "code", maelys_datalog_diag_code_name(d->code));
    (void)maelys_cli_json_key_string(json, "message", d->message);
    (void)maelys_cli_json_key_string(json, "phase", d->phase);
    (void)maelys_cli_json_key_string(json, "status", maelys_datalog_status_name(d->status));
    (void)maelys_cli_json_key_unsigned(json, "source", (uint64_t)d->source);
    (void)maelys_cli_json_key_unsigned(json, "present", d->present);
    if (d->hint[0]) (void)maelys_cli_json_key_string(json, "hint", d->hint);
    if (d->present & MAELYS_DATALOG_DIAGNOSTIC_LOCATION) {
        (void)maelys_cli_json_key_unsigned(json, "line", (uint64_t)d->line);
        (void)maelys_cli_json_key_unsigned(json, "column", (uint64_t)d->column);
        if (d->file[0]) (void)maelys_cli_json_key_string(json, "file", d->file);
    }
    if (d->present & MAELYS_DATALOG_DIAGNOSTIC_PREDICATE)
        (void)maelys_cli_json_key_string(json, "predicate", d->predicate);
    if (d->present & MAELYS_DATALOG_DIAGNOSTIC_CAPACITY) {
        (void)maelys_cli_json_key_unsigned(json, "observedCount", (uint64_t)d->observed_count);
        (void)maelys_cli_json_key_unsigned(json, "limit", (uint64_t)d->limit);
        (void)maelys_cli_json_key_unsigned(json, "limitKind", (uint64_t)d->limit_kind);
    }
    if (d->present & MAELYS_DATALOG_DIAGNOSTIC_ARITY) {
        (void)maelys_cli_json_key_unsigned(json, "arity", (uint64_t)d->arity);
        (void)maelys_cli_json_key_unsigned(json, "expectedArity", (uint64_t)d->expected_arity);
        (void)maelys_cli_json_key_unsigned(json, "observedArity", (uint64_t)d->observed_arity);
    }
    if (d->present & MAELYS_DATALOG_DIAGNOSTIC_DEPTH) {
        (void)maelys_cli_json_key_unsigned(json, "depth", (uint64_t)d->depth);
        (void)maelys_cli_json_key_unsigned(json, "depthLimit", (uint64_t)d->depth_limit);
    }
    if (d->present & MAELYS_DATALOG_DIAGNOSTIC_COMPARISON) {
        (void)maelys_cli_json_key_unsigned(json, "comparisonResult", d->comparison_result);
        (void)maelys_cli_json_key_unsigned(json, "expectedKind", d->expected_kind);
        (void)maelys_cli_json_key_unsigned(json, "lhsKind", d->lhs_kind);
        (void)maelys_cli_json_key_unsigned(json, "rhsKind", d->rhs_kind);
        (void)maelys_cli_json_key_unsigned(json, "comparisonOp", d->comparison_op);
    }
    if (d->present & MAELYS_DATALOG_DIAGNOSTIC_AGGREGATE) {
        (void)maelys_cli_json_key_unsigned(json, "termIndex", (uint64_t)d->term_index);
        (void)maelys_cli_json_key_unsigned(json, "aggregateLimit", (uint64_t)d->limit);
        if (!(d->present & MAELYS_DATALOG_DIAGNOSTIC_COMPARISON))
            (void)maelys_cli_json_key_unsigned(json, "lhsKind", d->lhs_kind);
    }
    if (d->present & MAELYS_DATALOG_DIAGNOSTIC_RULE)
        (void)maelys_cli_json_key_unsigned(json, "ruleId", (uint64_t)d->rule_id);
    if (d->present & (MAELYS_DATALOG_DIAGNOSTIC_CONTEXT |
                      MAELYS_DATALOG_DIAGNOSTIC_AGGREGATE)) {
        if (d->field[0]) (void)maelys_cli_json_key_string(json, "field", d->field);
        if (d->domain[0]) (void)maelys_cli_json_key_string(json, "domain", d->domain);
        if (d->token[0]) (void)maelys_cli_json_key_string(json, "token", d->token);
    }
    (void)maelys_cli_json_end_object(json);
}

static int verdict(maelys_cli_context_t *context, const char *code,
                   const char *message, const datalog_cli_error_t *error,
                   const maelys_datalog_diagnostic_t *diagnostic) {
    maelys_cli_json_writer_t json;
    maelys_cli_json_writer_init(&json);
    (void)maelys_cli_json_begin_object(&json);
    (void)maelys_cli_json_key_boolean(&json, "valid", 0);
    (void)maelys_cli_json_key(&json, "diagnostics");
    (void)maelys_cli_json_begin_array(&json);
    if (diagnostic) diagnostic_json(&json, diagnostic);
    else {
        (void)maelys_cli_json_begin_object(&json);
        (void)maelys_cli_json_key_string(&json, "code", code);
        (void)maelys_cli_json_key_string(&json, "message", message);
        if (error && error->has_index)
            (void)maelys_cli_json_key_unsigned(&json, "index", (uint64_t)error->index);
        (void)maelys_cli_json_end_object(&json);
    }
    (void)maelys_cli_json_end_array(&json);
    (void)maelys_cli_json_end_object(&json);
    return maelys_cli_succeed_writer(context, &json, message,
                                    MAELYS_CLI_EXIT_VIOLATIONS);
}

/* Returns 0 on success, -1 after emitting a failure, -2 for a check verdict. */
static int domains_load(maelys_cli_context_t *context, state_t *state,
                        int checking, datalog_cli_error_t *error) {
    size_t count = maelys_cli_option_count(context, "domain");
    if (!count) {
        (void)failure(context, MAELYS_CLI_CODE_VALIDATION_FAILED,
                      "at least one --domain is required");
        return -1;
    }
    state->domains = calloc(count, sizeof(*state->domains));
    if (!state->domains) {
        (void)failure(context, MAELYS_CLI_CODE_UNEXPECTED, "out of memory");
        return -1;
    }
    state->domain_count = count;
    for (size_t i = 0; i < count; ++i) {
        const char *path = maelys_cli_option_at(context, "domain", i);
        if (datalog_cli_domain_read(path, &state->domains[i], error) != 0) {
            if (checking && !error->parse_error && !error->io_error &&
                !error->internal_error) return -2;
            (void)failure(context, error->not_found ? MAELYS_CLI_CODE_NOT_FOUND
                          : error->io_error ? MAELYS_CLI_CODE_IO_FAILED
                          : error->internal_error ? MAELYS_CLI_CODE_UNEXPECTED
                          : MAELYS_CLI_CODE_VALIDATION_FAILED, error->message);
            return -1;
        }
        for (size_t j = 0; j < i; ++j)
            if (strcmp(state->domains[j].declaration.name,
                       state->domains[i].declaration.name) == 0) {
                (void)snprintf(error->message, sizeof(error->message),
                               "duplicate domain name");
                if (checking) return -2;
                (void)failure(context, MAELYS_CLI_CODE_VALIDATION_FAILED, error->message);
                return -1;
            }
        maelys_datalog_status_t rc = maelys_datalog_domain_register(
            &state->domains[i].declaration);
        if (rc != MAELYS_DATALOG_STATUS_OK) {
            (void)snprintf(error->message, sizeof(error->message),
                           "domain registration rejected: %s",
                           maelys_datalog_status_name(rc));
            if (checking && rc != MAELYS_DATALOG_STATUS_INTERNAL) return -2;
            (void)failure(context, rc == MAELYS_DATALOG_STATUS_INTERNAL
                          ? MAELYS_CLI_CODE_UNEXPECTED : MAELYS_CLI_CODE_VALIDATION_FAILED,
                          error->message);
            return -1;
        }
    }
    return 0;
}

static int policy_load(maelys_cli_context_t *context, state_t *state,
                       int checking, maelys_datalog_diagnostic_t *diagnostic) {
    const char *manifest = maelys_cli_option(context, "manifest");
    const char *file = maelys_cli_operand(context, 0u);
    if (!!manifest == !!file ||
        (manifest && maelys_cli_option(context, "policy-id")) ||
        (!manifest && (maelys_cli_flag(context, "allow-test-only") ||
                      maelys_cli_flag(context, "allow-undeclared-policy-atoms"))) ||
        (!manifest && state->domain_count != 1u)) {
        (void)failure(context, MAELYS_CLI_CODE_VALIDATION_FAILED,
                      "choose one POLICY or --manifest; manifest flags and multiple domains require --manifest");
        return -1;
    }
    maelys_datalog_status_t rc;
    if (manifest) {
        unsigned flags = 0;
        if (maelys_cli_flag(context, "allow-test-only"))
            flags |= MAELYS_DATALOG_PUBLIC_ALLOW_TEST_ONLY;
        if (maelys_cli_flag(context, "allow-undeclared-policy-atoms"))
            flags |= MAELYS_DATALOG_PUBLIC_ALLOW_UNDECLARED_POLICY_ATOMS;
        rc = maelys_datalog_policy_load_manifest(manifest, flags,
                                                 &state->policy, diagnostic);
    } else {
        size_t length = 0;
        if (read_source(file, &state->source, &length) != 0) {
            int saved = errno;
            if (saved == EINVAL)
                (void)failure(context, MAELYS_CLI_CODE_VALIDATION_FAILED,
                              "NUL byte in policy source");
            else if (saved == EFBIG)
                (void)failure(context, MAELYS_CLI_CODE_VALIDATION_FAILED,
                              "policy source exceeds 16 MiB");
            else if (saved == ENOMEM)
                (void)failure(context, MAELYS_CLI_CODE_UNEXPECTED,
                              "out of memory");
            else if (saved == ENOENT || saved == ENOTDIR) {
                char message[320];
                (void)snprintf(message, sizeof(message),
                               "policy file not found: %s", file);
                (void)failure(context, MAELYS_CLI_CODE_NOT_FOUND, message);
            }
            else (void)maelys_cli_fail_errno(context, MAELYS_CLI_CODE_IO_FAILED,
                                              saved, file);
            return -1;
        }
        const char *id = maelys_cli_option_or(context, "policy-id", "cli");
        rc = maelys_datalog_policy_load_inline(
            state->domains[0].declaration.name, id, state->source, length,
            &state->policy, diagnostic);
    }
    if (rc == MAELYS_DATALOG_STATUS_OK) return 0;
    if (manifest && rc == MAELYS_DATALOG_STATUS_NOT_FOUND) {
        struct stat metadata;
        if (stat(manifest, &metadata) != 0 &&
            (errno == ENOENT || errno == ENOTDIR)) {
            char message[320];
            (void)snprintf(message, sizeof(message),
                           "manifest file not found: %s", manifest);
            (void)failure(context, MAELYS_CLI_CODE_NOT_FOUND, message);
            return -1;
        }
    }
    if (checking && rc != MAELYS_DATALOG_STATUS_IO &&
        rc != MAELYS_DATALOG_STATUS_INTERNAL &&
        rc != MAELYS_DATALOG_STATUS_NOT_FOUND &&
        rc != MAELYS_DATALOG_STATUS_INVALID_ARGUMENT &&
        diagnostic->code != MAELYS_DATALOG_DIAG_MANIFEST_INVALID_JSON)
        return -2;
    (void)status_failure(context, rc, diagnostic);
    return -1;
}

static int make_session(maelys_cli_context_t *context, state_t *state,
                        size_t index, int explanations) {
    maelys_datalog_session_config_t *config = NULL;
    maelys_datalog_status_t rc = maelys_datalog_session_config_create(&config);
    if (rc == MAELYS_DATALOG_STATUS_OK && maelys_cli_option(context, "work-limit")) {
        uint64_t limit = 0;
        (void)maelys_cli_option_unsigned(context, "work-limit", &limit);
        rc = maelys_datalog_session_config_set_work_limit(config, limit);
    }
    if (rc == MAELYS_DATALOG_STATUS_OK && explanations)
        rc = maelys_datalog_session_config_set_explanation_workspace(
            config, MAELYS_DATALOG_EXPLAIN_TRUE | MAELYS_DATALOG_EXPLAIN_FALSE);
    if (rc == MAELYS_DATALOG_STATUS_OK)
        rc = maelys_datalog_session_create_configured(state->policy, index,
                                                       config, &state->session);
    (void)maelys_datalog_session_config_free(config);
    if (rc != MAELYS_DATALOG_STATUS_OK) {
        (void)status_failure(context, rc, NULL);
        return -1;
    }
    return 0;
}

static void identity_json(maelys_cli_json_writer_t *json, const char *policy,
                          const char *execution) {
    (void)maelys_cli_json_key(json, "policyFingerprint");
    if (policy) (void)maelys_cli_json_string(json, policy);
    else (void)maelys_cli_json_null(json);
    if (execution) (void)maelys_cli_json_key_string(json, "executionFingerprint", execution);
}

static maelys_datalog_status_t enabled_policy_count(
    const maelys_datalog_policy_t *policy, size_t *count) {
    maelys_datalog_status_t rc = maelys_datalog_policy_count(policy, count);
    /* The historical count accessor rejects an empty set. The ID accessor
     * distinguishes a live handle with no index 0 (NOT_FOUND) from a released
     * handle (INVALID_STATE), without interpreting engine-private storage. */
    if (rc == MAELYS_DATALOG_STATUS_INVALID_STATE) {
        const char *id = NULL;
        if (maelys_datalog_policy_id(policy, 0u, &id) == MAELYS_DATALOG_STATUS_NOT_FOUND) {
            *count = 0u;
            return MAELYS_DATALOG_STATUS_OK;
        }
    }
    return rc;
}

static int command_check(maelys_cli_context_t *context) {
    state_t state = {0};
    datalog_cli_error_t error = {0};
    maelys_datalog_diagnostic_t diagnostic = MAELYS_DATALOG_DIAGNOSTIC_INIT;
    int rc = domains_load(context, &state, 1, &error);
    if (rc == -2) {
        int result = verdict(context, "DOMAIN_INVALID", error.message, &error, NULL);
        cleanup(&state); return result;
    }
    if (rc != 0) { cleanup(&state); return 1; }
    rc = policy_load(context, &state, 1, &diagnostic);
    if (rc == -2) {
        int result = verdict(context, "POLICY_INVALID", diagnostic.message,
                             NULL, &diagnostic);
        cleanup(&state); return result;
    }
    if (rc != 0) { cleanup(&state); return 1; }
    size_t policy_count = 0, total_rules = 0;
    char fingerprint[MAELYS_DATALOG_PUBLIC_FINGERPRINT_BYTES];
    if (enabled_policy_count(state.policy, &policy_count) != MAELYS_DATALOG_STATUS_OK ||
        (policy_count && maelys_datalog_policy_fingerprint(state.policy, fingerprint) !=
                         MAELYS_DATALOG_STATUS_OK)) {
        cleanup(&state); return failure(context, MAELYS_CLI_CODE_UNEXPECTED,
                                        "policy introspection failed");
    }
    maelys_cli_json_writer_t json;
    maelys_cli_json_writer_init(&json);
    (void)maelys_cli_json_begin_object(&json);
    (void)maelys_cli_json_key_boolean(&json, "valid", 1);
    identity_json(&json, policy_count ? fingerprint : NULL, NULL);
    (void)maelys_cli_json_key_unsigned(&json, "policyCount", (uint64_t)policy_count);
    (void)maelys_cli_json_key(&json, "policies");
    (void)maelys_cli_json_begin_array(&json);
    for (size_t i = 0; i < policy_count; ++i) {
        size_t rules = 0;
        const char *id = NULL;
        if (maelys_datalog_policy_id(state.policy, i, &id) != MAELYS_DATALOG_STATUS_OK ||
            maelys_datalog_policy_stat_get(state.policy, i,
                MAELYS_DATALOG_POLICY_RULE_COUNT, &rules) != MAELYS_DATALOG_STATUS_OK) {
            maelys_cli_json_writer_clear(&json); cleanup(&state);
            return failure(context, MAELYS_CLI_CODE_UNEXPECTED,
                           "policy metadata unavailable");
        }
        total_rules += rules;
        (void)maelys_cli_json_begin_object(&json);
        (void)maelys_cli_json_key_unsigned(&json, "index", (uint64_t)i);
        (void)maelys_cli_json_key_string(&json, "policyId", id);
        (void)maelys_cli_json_key_unsigned(&json, "normalizedRuleCount", (uint64_t)rules);
        (void)maelys_cli_json_end_object(&json);
    }
    (void)maelys_cli_json_end_array(&json);
    (void)maelys_cli_json_key_unsigned(&json, "normalizedRuleCount", (uint64_t)total_rules);
    (void)maelys_cli_json_key(&json, "domains");
    (void)maelys_cli_json_begin_array(&json);
    for (size_t i = 0; i < state.domain_count; ++i) {
        const datalog_cli_domain_t *d = &state.domains[i];
        (void)maelys_cli_json_begin_object(&json);
        (void)maelys_cli_json_key_string(&json, "name", d->declaration.name);
        (void)maelys_cli_json_key(&json, "predicates");
        (void)maelys_cli_json_begin_array(&json);
        for (size_t j = 0; j < d->declaration.predicate_count; ++j) {
            const maelys_datalog_predicate_t *p = &d->predicates[j];
            const char *role = p->flags & MAELYS_DATALOG_PREDICATE_EDB ? "edb" :
                p->flags & MAELYS_DATALOG_PREDICATE_IDB ? "idb" : "policy_fact";
            (void)maelys_cli_json_begin_object(&json);
            (void)maelys_cli_json_key_string(&json, "name", p->name);
            (void)maelys_cli_json_key_unsigned(&json, "arity", (uint64_t)p->arity);
            (void)maelys_cli_json_key_string(&json, "role", role);
            (void)maelys_cli_json_key_boolean(&json, "query",
                !!(p->flags & MAELYS_DATALOG_PREDICATE_QUERY));
            (void)maelys_cli_json_end_object(&json);
        }
        (void)maelys_cli_json_end_array(&json);
        (void)maelys_cli_json_key(&json, "atoms");
        (void)maelys_cli_json_begin_array(&json);
        for (size_t j = 0; j < d->declaration.atom_count; ++j)
            (void)maelys_cli_json_string(&json, d->atoms[j]);
        (void)maelys_cli_json_end_array(&json);
        (void)maelys_cli_json_end_object(&json);
    }
    (void)maelys_cli_json_end_array(&json);
    (void)maelys_cli_json_end_object(&json);
    cleanup(&state);
    return maelys_cli_succeed_writer(context, &json, "Policy valid.", MAELYS_CLI_EXIT_OK);
}

static int load_policy(maelys_cli_context_t *context, state_t *state,
                    datalog_cli_error_t *error) {
    maelys_datalog_diagnostic_t diagnostic = MAELYS_DATALOG_DIAGNOSTIC_INIT;
    if (domains_load(context, state, 0, error) != 0) return -1;
    if (policy_load(context, state, 0, &diagnostic) != 0) return -1;
    return 0;
}

static int command_fingerprint(maelys_cli_context_t *context) {
    state_t state = {0};
    datalog_cli_error_t error = {0};
    if (load_policy(context, &state, &error) != 0) { cleanup(&state); return 1; }
    char policy[MAELYS_DATALOG_PUBLIC_FINGERPRINT_BYTES];
    if (maelys_datalog_policy_fingerprint(state.policy, policy) != MAELYS_DATALOG_STATUS_OK) {
        cleanup(&state); return failure(context, MAELYS_CLI_CODE_UNEXPECTED,
                                        "policy fingerprint unavailable");
    }
    if (make_session(context, &state, 0u, 0) != 0) { cleanup(&state); return 1; }
    char execution[MAELYS_DATALOG_PUBLIC_FINGERPRINT_BYTES];
    if (maelys_datalog_session_execution_fingerprint(state.session, execution) !=
        MAELYS_DATALOG_STATUS_OK) {
        cleanup(&state); return failure(context, MAELYS_CLI_CODE_UNEXPECTED,
                                        "execution fingerprint unavailable");
    }
    maelys_cli_json_writer_t json;
    maelys_cli_json_writer_init(&json);
    (void)maelys_cli_json_begin_object(&json);
    identity_json(&json, policy, execution);
    (void)maelys_cli_json_end_object(&json);
    char human[2u * MAELYS_DATALOG_PUBLIC_FINGERPRINT_BYTES + 64u];
    int length = snprintf(human, sizeof(human),
                          "policyFingerprint: %s\nexecutionFingerprint: %s",
                          policy, execution);
    if (length < 0 || (size_t)length >= sizeof(human)) {
        maelys_cli_json_writer_clear(&json);
        cleanup(&state);
        return failure(context, MAELYS_CLI_CODE_UNEXPECTED,
                       "fingerprint output unavailable");
    }
    cleanup(&state);
    return maelys_cli_succeed_writer(context, &json, human, MAELYS_CLI_EXIT_OK);
}

static int solve_common(maelys_cli_context_t *context, state_t *state,
                        int explanations) {
    datalog_cli_error_t error = {0};
    if (load_policy(context, state, &error) != 0) return -1;
    const char *facts_path = maelys_cli_option(context, "facts");
    if (datalog_cli_facts_read(facts_path, &state->domains[0], &state->facts,
                               &error) != 0) {
        (void)failure(context, error.not_found ? MAELYS_CLI_CODE_NOT_FOUND :
                      error.io_error ? MAELYS_CLI_CODE_IO_FAILED :
                      error.internal_error ? MAELYS_CLI_CODE_UNEXPECTED :
                      MAELYS_CLI_CODE_VALIDATION_FAILED, error.message);
        return -1;
    }
    if (make_session(context, state, 0u, explanations) != 0) return -1;
    maelys_datalog_diagnostic_t diagnostic = MAELYS_DATALOG_DIAGNOSTIC_INIT;
    maelys_datalog_status_t rc = maelys_datalog_session_solve(
        state->session, state->facts.facts, state->facts.count,
        &state->result, &diagnostic);
    if (rc != MAELYS_DATALOG_STATUS_OK) {
        (void)status_failure(context, rc, &diagnostic);
        return -1;
    }
    return 0;
}

static const maelys_datalog_predicate_t *query_predicate(
    const datalog_cli_domain_t *domain, const char *text) {
    char *slash = strchr(text, '/');
    size_t length = slash ? (size_t)(slash - text) : strlen(text);
    for (size_t i = 0; i < domain->declaration.predicate_count; ++i) {
        const maelys_datalog_predicate_t *p = &domain->predicates[i];
        if (strlen(p->name) != length || memcmp(p->name, text, length) != 0 ||
            !(p->flags & MAELYS_DATALOG_PREDICATE_QUERY)) continue;
        if (!slash) return p;
        char expected[32];
        (void)snprintf(expected, sizeof(expected), "%zu", p->arity);
        if (strcmp(slash + 1, expected) == 0) return p;
    }
    return NULL;
}

typedef struct {
    char *data;
    size_t length, capacity;
    int failed;
} human_text_t;

static void human_appendn(human_text_t *out, const char *value, size_t length) {
    if (out->failed) return;
    if (length > SIZE_MAX - out->length - 1u) { out->failed = 1; return; }
    size_t needed = out->length + length + 1u;
    if (needed > out->capacity) {
        size_t capacity = out->capacity ? out->capacity : 256u;
        while (capacity < needed) {
            if (capacity > SIZE_MAX / 2u) { capacity = needed; break; }
            capacity *= 2u;
        }
        char *grown = realloc(out->data, capacity);
        if (!grown) { out->failed = 1; return; }
        out->data = grown;
        out->capacity = capacity;
    }
    memcpy(out->data + out->length, value, length);
    out->length += length;
    out->data[out->length] = 0;
}

static void human_append(human_text_t *out, const char *value) {
    human_appendn(out, value, strlen(value));
}

static void human_symbol(human_text_t *out, const char *value, size_t length) {
    static const char digits[] = "0123456789abcdef";
    human_append(out, "\"");
    for (size_t i = 0; i < length; ++i) {
        unsigned char byte = (unsigned char)value[i];
        if (byte == '"' || byte == '\\') {
            char escaped[] = {'\\', (char)byte};
            human_appendn(out, escaped, sizeof(escaped));
        } else if (byte < 0x20u) {
            char escaped[] = {'\\', 'u', '0', '0', digits[byte >> 4],
                              digits[byte & 0xf]};
            human_appendn(out, escaped, sizeof(escaped));
        } else human_appendn(out, (const char *)&value[i], 1u);
    }
    human_append(out, "\"");
}

static int command_queries(maelys_cli_context_t *context) {
    state_t state = {0};
    datalog_cli_error_t error = {0};
    if (load_policy(context, &state, &error) != 0) { cleanup(&state); return 1; }
    size_t policy_count = 0;
    char fingerprint[MAELYS_DATALOG_PUBLIC_FINGERPRINT_BYTES];
    maelys_datalog_status_t rc = enabled_policy_count(state.policy, &policy_count);
    if (rc == MAELYS_DATALOG_STATUS_OK && policy_count)
        rc = maelys_datalog_policy_fingerprint(state.policy, fingerprint);
    if (rc != MAELYS_DATALOG_STATUS_OK) {
        cleanup(&state); return status_failure(context, rc, NULL);
    }
    maelys_cli_json_writer_t json;
    maelys_cli_json_writer_init(&json);
    human_text_t human = {0};
    (void)maelys_cli_json_begin_object(&json);
    identity_json(&json, policy_count ? fingerprint : NULL, NULL);
    (void)maelys_cli_json_key(&json, "policies");
    (void)maelys_cli_json_begin_array(&json);
    /* Inspect one prepared policy at a time. Names are borrowed from the live
     * session; copy them into the buffered output before releasing it. */
    for (size_t i = 0; i < policy_count; ++i) {
        if (make_session(context, &state, i, 0) != 0) {
            free(human.data); maelys_cli_json_writer_clear(&json);
            cleanup(&state); return 1;
        }
        const maelys_datalog_program_t *program = NULL;
        maelys_datalog_program_info_t info = {0};
        size_t count = 0;
        rc = maelys_datalog_session_program(state.session, &program);
        if (rc == MAELYS_DATALOG_STATUS_OK)
            rc = maelys_datalog_program_info(program, &info);
        if (rc == MAELYS_DATALOG_STATUS_OK)
            rc = maelys_datalog_program_query_count(program, &count);
        if (rc != MAELYS_DATALOG_STATUS_OK) goto failed;
        (void)maelys_cli_json_begin_object(&json);
        (void)maelys_cli_json_key_unsigned(&json, "index", (uint64_t)i);
        (void)maelys_cli_json_key_string(&json, "policyId", info.policy_id);
        (void)maelys_cli_json_key_string(&json, "domain", info.domain);
        (void)maelys_cli_json_key(&json, "queries");
        (void)maelys_cli_json_begin_array(&json);
        human_append(&human, "policy ");
        human_symbol(&human, info.policy_id, strlen(info.policy_id));
        human_append(&human, " (domain ");
        human_append(&human, info.domain);
        human_append(&human, "):\n");
        for (size_t j = 0; j < count; ++j) {
            maelys_datalog_predicate_t predicate = {0};
            rc = maelys_datalog_program_query(program, j, &predicate);
            if (rc != MAELYS_DATALOG_STATUS_OK) goto failed;
            (void)maelys_cli_json_begin_object(&json);
            (void)maelys_cli_json_key_string(&json, "predicate", predicate.name);
            (void)maelys_cli_json_key_unsigned(&json, "arity", (uint64_t)predicate.arity);
            (void)maelys_cli_json_end_object(&json);
            char arity[32];
            int length = snprintf(arity, sizeof(arity), "/%zu\n", predicate.arity);
            if (length < 0 || (size_t)length >= sizeof(arity)) {
                rc = MAELYS_DATALOG_STATUS_INTERNAL; goto failed;
            }
            human_append(&human, "  ");
            human_append(&human, predicate.name);
            human_appendn(&human, arity, (size_t)length);
        }
        if (!count) human_append(&human, "  (no authorized queries)\n");
        (void)maelys_cli_json_end_array(&json);
        (void)maelys_cli_json_end_object(&json);
        rc = maelys_datalog_session_free(state.session);
        if (rc != MAELYS_DATALOG_STATUS_OK) goto failed;
        state.session = NULL;
    }
    (void)maelys_cli_json_end_array(&json);
    (void)maelys_cli_json_end_object(&json);
    if (!policy_count) human_append(&human, "No enabled policies.\n");
    if (human.failed) { rc = MAELYS_DATALOG_STATUS_INTERNAL; goto failed; }
    {
        int result = maelys_cli_succeed_writer(context, &json, human.data,
                                               MAELYS_CLI_EXIT_OK);
        free(human.data); cleanup(&state);
        return result;
    }
failed:
    free(human.data); maelys_cli_json_writer_clear(&json);
    cleanup(&state); return status_failure(context, rc, NULL);
}

static int command_solve(maelys_cli_context_t *context) {
    state_t state = {0};
    if (solve_common(context, &state, 0) != 0) { cleanup(&state); return 1; }
    const datalog_cli_domain_t *domain = &state.domains[0];
    size_t selected = maelys_cli_option_count(context, "query");
    for (size_t i = 0; i < selected; ++i) {
        if (!query_predicate(domain, maelys_cli_option_at(context, "query", i))) {
            cleanup(&state);
            return failure(context, MAELYS_CLI_CODE_NOT_FOUND,
                           "unknown or non-query predicate");
        }
    }
    char policy[MAELYS_DATALOG_PUBLIC_FINGERPRINT_BYTES];
    char execution[MAELYS_DATALOG_PUBLIC_FINGERPRINT_BYTES];
    size_t derived = 0;
    if (maelys_datalog_policy_fingerprint(state.policy, policy) != MAELYS_DATALOG_STATUS_OK ||
        maelys_datalog_session_execution_fingerprint(state.session, execution) !=
            MAELYS_DATALOG_STATUS_OK ||
        maelys_datalog_result_derived_fact_count(state.result, &derived) !=
            MAELYS_DATALOG_STATUS_OK) {
        cleanup(&state); return failure(context, MAELYS_CLI_CODE_UNEXPECTED,
                                        "result introspection failed");
    }
    maelys_cli_json_writer_t json;
    maelys_cli_json_writer_init(&json);
    human_text_t human = {0};
    (void)maelys_cli_json_begin_object(&json);
    identity_json(&json, policy, execution);
    (void)maelys_cli_json_key_unsigned(&json, "derivedFactCount", (uint64_t)derived);
    (void)maelys_cli_json_key(&json, "queries");
    (void)maelys_cli_json_begin_array(&json);
    size_t iterations = selected ? selected : domain->declaration.predicate_count;
    for (size_t i = 0; i < iterations; ++i) {
        const maelys_datalog_predicate_t *p = selected
            ? query_predicate(domain, maelys_cli_option_at(context, "query", i))
            : &domain->predicates[i];
        if (!(p->flags & MAELYS_DATALOG_PREDICATE_QUERY)) continue;
        size_t count = 0;
        maelys_datalog_status_t rc = maelys_datalog_result_enumerate(
            state.result, p->name, p->arity, NULL, 0u, &count);
        maelys_datalog_fact_view_t *views = count ? calloc(count, sizeof(*views)) : NULL;
        if (rc == MAELYS_DATALOG_STATUS_OK && count && !views)
            rc = MAELYS_DATALOG_STATUS_INTERNAL;
        if (rc == MAELYS_DATALOG_STATUS_OK && count)
            rc = maelys_datalog_result_enumerate(state.result, p->name,
                                                  p->arity, views, count, &count);
        if (rc != MAELYS_DATALOG_STATUS_OK) {
            free(views); free(human.data); maelys_cli_json_writer_clear(&json);
            cleanup(&state);
            return status_failure(context, rc, NULL);
        }
        char heading[128];
        int heading_length = snprintf(heading, sizeof(heading),
                                      "%s/%zu (%zu facts):\n", p->name,
                                      p->arity, count);
        if (heading_length < 0 || (size_t)heading_length >= sizeof(heading))
            human.failed = 1;
        else human_appendn(&human, heading, (size_t)heading_length);
        if (!count) human_append(&human, "  (none)\n");
        (void)maelys_cli_json_begin_object(&json);
        (void)maelys_cli_json_key_string(&json, "predicate", p->name);
        (void)maelys_cli_json_key_unsigned(&json, "arity", (uint64_t)p->arity);
        (void)maelys_cli_json_key(&json, "facts");
        (void)maelys_cli_json_begin_array(&json);
        for (size_t j = 0; j < count; ++j) {
            (void)maelys_cli_json_begin_array(&json);
            human_append(&human, "  ");
            human_append(&human, p->name);
            human_append(&human, "(");
            for (size_t k = 0; k < views[j].arity; ++k) {
                maelys_datalog_term_view_t term = views[j].terms[k];
                (void)maelys_cli_json_begin_object(&json);
                if (k) human_append(&human, ", ");
                if (term.kind == MAELYS_DATALOG_VALUE_SYMBOL) {
                    const char *text = NULL; size_t length = 0;
                    rc = maelys_datalog_result_symbol_text(state.result,
                        term.as.symbol_id, &text, &length);
                    if (rc != MAELYS_DATALOG_STATUS_OK) {
                        free(views); free(human.data);
                        maelys_cli_json_writer_clear(&json);
                        cleanup(&state); return status_failure(context, rc, NULL);
                    }
                    human_symbol(&human, text, length);
                    (void)maelys_cli_json_key_string(&json, "kind", "symbol");
                    (void)maelys_cli_json_key(&json, "value");
                    (void)maelys_cli_json_stringn(&json, text, length);
                } else if (term.kind == MAELYS_DATALOG_VALUE_INTEGER) {
                    char number[32];
                    int length = snprintf(number, sizeof(number), "%" PRId64,
                                          term.as.integer);
                    if (length < 0 || (size_t)length >= sizeof(number))
                        human.failed = 1;
                    else human_appendn(&human, number, (size_t)length);
                    (void)maelys_cli_json_key_string(&json, "kind", "integer");
                    (void)maelys_cli_json_key_integer(&json, "value", term.as.integer);
                } else {
                    human_append(&human, term.as.boolean ? "true" : "false");
                    (void)maelys_cli_json_key_string(&json, "kind", "boolean");
                    (void)maelys_cli_json_key_boolean(&json, "value", term.as.boolean);
                }
                (void)maelys_cli_json_end_object(&json);
            }
            (void)maelys_cli_json_end_array(&json);
            human_append(&human, ").\n");
        }
        free(views);
        (void)maelys_cli_json_end_array(&json);
        (void)maelys_cli_json_end_object(&json);
    }
    (void)maelys_cli_json_end_array(&json);
    (void)maelys_cli_json_end_object(&json);
    if (!human.length && !human.failed)
        human_append(&human, "No query predicates declared.\n");
    cleanup(&state);
    if (human.failed) {
        free(human.data); maelys_cli_json_writer_clear(&json);
        return failure(context, MAELYS_CLI_CODE_UNEXPECTED, "out of memory");
    }
    int result = maelys_cli_succeed_writer(context, &json, human.data,
                                           MAELYS_CLI_EXIT_OK);
    free(human.data);
    return result;
}

static int command_explain(maelys_cli_context_t *context) {
    state_t state = {0};
    if (solve_common(context, &state, 1) != 0) { cleanup(&state); return 1; }
    const char *name = maelys_cli_operand(context, 1u);
    const maelys_datalog_predicate_t *predicate = query_predicate(&state.domains[0], name);
    if (!predicate) {
        cleanup(&state); return failure(context, MAELYS_CLI_CODE_NOT_FOUND,
                                        "unknown or non-query predicate");
    }
    size_t term_count = maelys_cli_operand_count(context) - 2u;
    if (term_count != predicate->arity) {
        cleanup(&state); return failure(context, MAELYS_CLI_CODE_VALIDATION_FAILED,
                                        "query term count differs from predicate arity");
    }
    maelys_datalog_value_t terms[MAELYS_DATALOG_PUBLIC_MAX_TERMS] = {0};
    char *owned[MAELYS_DATALOG_PUBLIC_MAX_TERMS] = {0};
    for (size_t i = 0; i < term_count; ++i) {
        const char *value = maelys_cli_operand(context, i + 2u);
        owned[i] = malloc(strlen(value) + 1u);
        if (!owned[i]) {
            for (size_t j = 0; j < i; ++j) free(owned[j]);
            cleanup(&state); return failure(context, MAELYS_CLI_CODE_UNEXPECTED,
                                            "out of memory");
        }
        strcpy(owned[i], value);
        if (datalog_cli_term_parse(owned[i], &terms[i]) != 0) {
            for (size_t j = 0; j <= i; ++j) free(owned[j]);
            cleanup(&state); return failure(context, MAELYS_CLI_CODE_VALIDATION_FAILED,
                                            "invalid query term");
        }
    }
    int present = 0;
    maelys_datalog_status_t rc = maelys_datalog_result_query(
        state.result, predicate->name, terms, term_count, &present);
    size_t required = 0;
    char *document = NULL;
    size_t why = 0;
    (void)maelys_cli_option_choice(context, "why", &why);
    if (rc == MAELYS_DATALOG_STATUS_OK) {
        if (why == 0u) rc = maelys_datalog_result_explain_true_text(
            state.result, predicate->name, terms, term_count, NULL, 0u, &required);
        else rc = maelys_datalog_result_explain_false_text(
            state.result, predicate->name, terms, term_count, NULL, 0u, &required);
    }
    if (rc == MAELYS_DATALOG_STATUS_OK) {
        document = malloc(required + 1u);
        if (!document) rc = MAELYS_DATALOG_STATUS_INTERNAL;
    }
    if (rc == MAELYS_DATALOG_STATUS_OK) {
        if (why == 0u) rc = maelys_datalog_result_explain_true_text(
            state.result, predicate->name, terms, term_count,
            document, required + 1u, &required);
        else rc = maelys_datalog_result_explain_false_text(
            state.result, predicate->name, terms, term_count,
            document, required + 1u, &required);
    }
    if (rc == MAELYS_DATALOG_STATUS_PAYLOAD_TOO_LARGE) {
        char *exact = realloc(document, required + 1u);
        if (!exact) rc = MAELYS_DATALOG_STATUS_INTERNAL;
        else {
            document = exact;
            if (why == 0u) rc = maelys_datalog_result_explain_true_text(
                state.result, predicate->name, terms, term_count,
                document, required + 1u, &required);
            else rc = maelys_datalog_result_explain_false_text(
                state.result, predicate->name, terms, term_count,
                document, required + 1u, &required);
        }
    }
    for (size_t i = 0; i < term_count; ++i) free(owned[i]);
    if (rc != MAELYS_DATALOG_STATUS_OK) {
        free(document); cleanup(&state); return status_failure(context, rc, NULL);
    }
    char policy[MAELYS_DATALOG_PUBLIC_FINGERPRINT_BYTES];
    char execution[MAELYS_DATALOG_PUBLIC_FINGERPRINT_BYTES];
    (void)maelys_datalog_policy_fingerprint(state.policy, policy);
    (void)maelys_datalog_session_execution_fingerprint(state.session, execution);
    maelys_cli_json_writer_t json;
    maelys_cli_json_writer_init(&json);
    (void)maelys_cli_json_begin_object(&json);
    identity_json(&json, policy, execution);
    (void)maelys_cli_json_key_string(&json, "predicate", predicate->name);
    (void)maelys_cli_json_key_boolean(&json, "present", present);
    (void)maelys_cli_json_key_string(&json, "why", why == 0u ? "true" : "false");
    (void)maelys_cli_json_key_string(&json, "document", document);
    (void)maelys_cli_json_end_object(&json);
    int result = maelys_cli_succeed_writer(context, &json, document,
                                           MAELYS_CLI_EXIT_OK);
    free(document); cleanup(&state);
    return result;
}

static const char *const why_choices[] = {"true", "false", NULL};
static const maelys_cli_operand_t policy_operand[] = {
    {MAELYS_CLI_OPERAND_OPTIONAL("POLICY", "Inline policy source file.")},
};
static const maelys_cli_operand_t explain_operands[] = {
    {MAELYS_CLI_OPERAND("POLICY", "Inline policy source file.")},
    {MAELYS_CLI_OPERAND("PREDICATE", "Queryable predicate name.")},
    {MAELYS_CLI_OPERAND_REST("TERMS", "Typed query terms: 3, true or quoted symbol.")},
};
static const maelys_cli_option_t policy_options[] = {
    {MAELYS_CLI_PATH("domain", "FILE", "Domain JSON declaration."), .required = 1, .repeatable = 1},
    {MAELYS_CLI_PATH("manifest", "FILE", "Load a manifest as one policy set.")},
    {MAELYS_CLI_STRING("policy-id", "ID", "Inline policy identifier.")},
    {MAELYS_CLI_FLAG("allow-test-only", "Admit test-only manifest entries."), .depends_on = "manifest"},
    {MAELYS_CLI_FLAG("allow-undeclared-policy-atoms", "Admit policy-local atoms."), .depends_on = "manifest"},
};
static const maelys_cli_option_t fingerprint_options[] = {
    {MAELYS_CLI_PATH("domain", "FILE", "Domain JSON declaration."), .required = 1},
    {MAELYS_CLI_STRING("policy-id", "ID", "Inline policy identifier.")},
    {MAELYS_CLI_UNSIGNED("work-limit", "N", "Cooperative work limit.", 1u, 0u)},
};
static const maelys_cli_option_t solve_options[] = {
    {MAELYS_CLI_PATH("domain", "FILE", "Domain JSON declaration."), .required = 1},
    {MAELYS_CLI_PATH("facts", "FILE", "Closed EDB facts."), .required = 1},
    {MAELYS_CLI_STRING("policy-id", "ID", "Inline policy identifier.")},
    {MAELYS_CLI_STRING("query", "PRED[/ARITY]", "Query a declared predicate."), .repeatable = 1},
    {MAELYS_CLI_UNSIGNED("work-limit", "N", "Cooperative work limit.", 1u, 0u)},
};
static const maelys_cli_option_t explain_options[] = {
    {MAELYS_CLI_PATH("domain", "FILE", "Domain JSON declaration."), .required = 1},
    {MAELYS_CLI_PATH("facts", "FILE", "Closed EDB facts."), .required = 1},
    {MAELYS_CLI_CHOICE("why", "Explain presence or absence.", why_choices), .required = 1},
    {MAELYS_CLI_STRING("policy-id", "ID", "Inline policy identifier.")},
    {MAELYS_CLI_UNSIGNED("work-limit", "N", "Cooperative work limit.", 1u, 0u)},
};
static const maelys_cli_command_t commands[] = {
    {MAELYS_CLI_READ("check", "check", "Validate a domain and policy; exit 2 reports rejection.",
                     command_check), MAELYS_CLI_OPERANDS(policy_operand),
     MAELYS_CLI_OPTIONS(policy_options), MAELYS_CLI_SCHEMA(datalog_check_schema)},
    {MAELYS_CLI_READ("queries", "queries", "List each policy's effectively authorized queries.",
                     command_queries), MAELYS_CLI_OPERANDS(policy_operand),
     MAELYS_CLI_OPTIONS(policy_options), MAELYS_CLI_SCHEMA(datalog_queries_schema)},
    {MAELYS_CLI_READ("fingerprint", "fingerprint", "Read policy and execution identities.",
                     command_fingerprint), MAELYS_CLI_OPERANDS(policy_operand),
     MAELYS_CLI_OPTIONS(fingerprint_options), MAELYS_CLI_SCHEMA(datalog_fingerprint_schema)},
    {MAELYS_CLI_READ("solve", "solve", "Solve an inline policy against one EDB batch.",
                     command_solve), MAELYS_CLI_OPERANDS(policy_operand),
     MAELYS_CLI_OPTIONS(solve_options), MAELYS_CLI_SCHEMA(datalog_solve_schema)},
    {MAELYS_CLI_READ("explain", "explain", "Explain a typed query against a solved policy.",
                     command_explain), MAELYS_CLI_OPERANDS(explain_operands),
     MAELYS_CLI_OPTIONS(explain_options), MAELYS_CLI_SCHEMA(datalog_explain_schema)},
};

int main(int argc, char **argv) {
    const maelys_cli_app_t app = {
        .program = "maelys-datalog", .product = "Maelys Datalog",
        .version = DATALOG_CLI_VERSION,
        .summary = "Validate, solve and explain bounded Datalog policies.",
        .commands = commands, .command_count = MAELYS_CLI_COUNT(commands),
    };
    return maelys_cli_main(&app, argc, argv);
}
